FROM node:22-bookworm-slim AS base


RUN groupadd -g 972 docker || groupmod -g 972 docker \
  && usermod -aG docker node

RUN apt update -y && apt install -y \
  curl \
  git \
  gh \
  ffmpeg

RUN npm install -g bun@1.3.10

RUN bunx playwright install-deps chromium

FROM base AS builder
USER node
WORKDIR /app

COPY --chown=node:node package.json bun.lock ./

RUN bun i --frozen-lockfile

RUN bunx playwright install chromium

FROM builder AS runner
USER node
WORKDIR /app

EXPOSE 5173

ENTRYPOINT sleep infinity
