FROM node:22-bookworm AS base
RUN npm install -g bun@1.3.10

RUN bunx playwright install-deps chromium

FROM base AS builder
USER node
WORKDIR /app

COPY --chown=node:node package.json bun.lock ./

RUN bun i --frozen-lockfile

RUN bunx playwright install chromium

COPY --chown=node:node . .

FROM builder AS runner
USER node
WORKDIR /app

ENTRYPOINT bun run test:ci
