FROM node:22-alpine3.23 AS base

ARG VITE_BUILD_MODE=prod

RUN npm install -g bun@1.3.8

FROM base AS build

WORKDIR /build

COPY package.json bun.lock ./

RUN bun i --frozen-lockfile --production

COPY . .

RUN bun run build --mode $VITE_BUILD_MODE

FROM nginx:1.29.4-alpine-slim  AS production
RUN apk add curl

COPY --from=build /build/nginx /etc/nginx
COPY --from=build /build/build/frontend /usr/share/nginx/html/site

EXPOSE 5173

HEALTHCHECK --interval=10s --timeout=30s --start-period=20s --retries=3 CMD ["curl", "-f", "http://0.0.0.0:5173"]
