import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { consola } from "consola";

// ============================================================================
// CONFIGURAÇÕES
// ============================================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, "..");
const publicImagesDir = path.join(projectRoot, "public", "images");
const outputTypeFile = path.join(projectRoot, "src", "types", "images-types.generated.ts");

// ============================================================================
// UTILITÁRIOS
// ============================================================================

/**
 * Varre o diretório recursivamente e retorna todos os arquivos.
 */
async function getAllFiles(dirPath: string, arrayOfFiles: string[] = [], baseDir = dirPath): Promise<string[]> {
	const files = await fs.readdir(dirPath);

	for (const file of files) {
		const fullPath = path.join(dirPath, file);
		const stat = await fs.stat(fullPath);

		if (stat.isDirectory()) {
			await getAllFiles(fullPath, arrayOfFiles, baseDir);
		} else {
			const relativePath = `/${path.relative(baseDir, fullPath).replace(/\\/g, "/")}`;

			if (!file.startsWith(".")) {
				arrayOfFiles.push(relativePath);
			}
		}
	}

	return arrayOfFiles;
}

// ============================================================================
// FUNÇÃO PRINCIPAL
// ============================================================================

/**
 * Gera o arquivo de tipos das imagens disponíveis.
 */
async function generateTypeDefinition(): Promise<void> {
	try {
		consola.box("📸 Gerador de Tipos de Imagens");

		consola.start(`Escaneando diretório: ${publicImagesDir}`);
		const filePaths = await getAllFiles(publicImagesDir);
		consola.success(`Encontrados ${filePaths.length} arquivo(s)`);

		if (filePaths.length === 0) {
			consola.warn("⚠️  Nenhum arquivo encontrado. Gerando tipo como 'string'.");
		}

		const typeContent = `// This file is auto-generated by scripts/create-images-type.ts\n// Do not edit manually!\n\nexport type ImageTypes = ${
			filePaths.length > 0 ? filePaths.map((p) => `"${p}"`).join(" | ") : "string"
		};\n`;

		await fs.mkdir(path.dirname(outputTypeFile), { recursive: true });
		await fs.writeFile(outputTypeFile, typeContent, "utf8");

		consola.success("✨ Tipos gerados com sucesso!");
		consola.info(`Arquivo salvo em: ${outputTypeFile}`);
	} catch (error) {
		consola.error("❌ Erro ao gerar tipos de imagens:");
		consola.error(error);
		process.exit(1);
	}
}

// ============================================================================
// EXECUÇÃO
// ============================================================================

generateTypeDefinition();
